plugins:
  - jekyll-seo-tag

theme: jekyll-theme-primer
title: Nicholas Kissel
tagline: A personal site
description: A personal site
author: Nicholas Kissel
markdown: kramdown
auto_ids: false
#url: nkissel.github.io
