plugins:
  - jekyll-seo-tag

theme: jekyll-theme-primer
title: Nicholas Kissel
tagline: A personal site
description: A personal site
author: Nicholas Kissel
#url: nkissel.github.io

markdown: kramdown
kramdown:
  auto_ids: true