---
title: "Papers & Presentations"
---

```{r makefunction, echo=FALSE}
library(bibtex)
generate_publication_html <- function(bib_data) {
  html_output <- ""
  
  for (i in seq_along(bib_data)) {
    # Extract fields safely
    entry <- bib_data[[i]]
    title <- if (!is.null(entry$title)) entry$title else "No title"
    authors <- if (!is.null(entry$author)) {
      paste(sapply(entry$author, function(author) paste(author)), collapse = ", ")
    } else {
      "No authors"
    }
    year <- if (!is.null(entry$year)) entry$year else "No year"
    journal <- if (!is.null(entry$journal)) entry$journal else "arXiv"
    url <- if (!is.null(entry$url)) entry$url else NULL
    
    # Create the card structure
    # card <- paste0(
    #   '<div class="card" style="margin: 30px; padding: 15px; border-radius: 5px;">\n',
    #   '<h6>', title, '</h6>\n',
    #   '<p style="margin-bottom: 5px;">', authors, '</p>\n',
    #   '<p>', journal, ', ', year, '</p>\n'
    # )
    
    card <- paste0(
      '<div class="card bg-light mb-3" style="margin: 30px; border-radius: 5px;">\n',
      '<div class="card-header" style="background-color:var(--bs-body-background)">', title, '</div>\n',
      '<div class="card-body">\n',
      '<p class="card-text">', authors, '</p>\n',
      '<p class="card-text">', journal, ', ', year, '</p>\n'
    )
    
    # Add a button for the link if a URL is present
    if (!is.null(url)) {
      card <- paste0(card,
                     '<a href="', url, '" target="_blank">',
                     '<button class="btn btn-outline-dark" type="button" style="border-radius:5px;position-bottom:0px;margin-bottom:0px;">Paper</button></a>')
    }
    
    card <- paste0(card, '</div>\n</div>\n')
    html_output <- paste0(html_output, card)
  }
  
  return(html_output)
}
```

## Preprints

```{r preprint, echo=FALSE, results='asis'}

# Read the .bib file
bib_data <- rev(read.bib("preprint.bib"))

# Generate the HTML and print it
html <- generate_publication_html(bib_data)
cat(html)

```

## Journal publications

```{r journal, echo=FALSE, results='asis'}

# Read the .bib file
bib_data <- rev(read.bib("journal.bib"))

# Generate the HTML and print it
html <- generate_publication_html(bib_data)
cat(html)

```






